/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export type Lessons =
  | {
      title: string;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export type Courses =
  | {
      name?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      additionalInfo?:
        | {
            icon?: string | null;
            title: string;
            value: string;
            id?: string | null;
          }[]
        | null;
      lessonsSection?: {
        title?: string | null;
        description?: string | null;
        showLessonNumbers?: boolean | null;
        lessons?: Lessons;
      };
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export type Schedules =
  | {
      title?: string | null;
      description?: string | null;
      /**
       * Vyberte kurz - v termínech pak můžete vybírat lekce
       */
      courseIndex?: string | null;
      status?: ServiceStatus;
      hasLimitedSpots?: boolean | null;
      numberOfSpots?: number | null;
      scheduleItems?:
        | {
            startDate: string;
            endDate: string;
            /**
             * Vyberte lekci nebo zadejte vlastní název
             */
            lesson: string;
            notes?: string | null;
            status?: ServiceStatus;
            hasLimitedSpots?: boolean | null;
            numberOfSpots?: number | null;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceStatus".
 */
export type ServiceStatus = ('scheduled' | 'open' | 'booked' | 'cancelled') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    reviews: Review;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    homePage: HomePage;
    servicesPage: ServicesPage;
    weeklyScheduledServicesPage: WeeklyScheduledServicesPage;
    aboutPage: AboutPage;
    contactPage: ContactPage;
    header: Header;
    footer: Footer;
    announcement: Announcement;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    weeklyScheduledServicesPage: WeeklyScheduledServicesPageSelect<false> | WeeklyScheduledServicesPageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
  };
  locale: 'cs' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Automaticky generovaný z názvu. Lze upravit.
   */
  slug: string;
  icon?: {
    fileIcon?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  duration?: string | null;
  price?: string | null;
  location?: string | null;
  additionalInfo?:
    | {
        icon?: string | null;
        title: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  serviceType?: ('courses' | 'lessons') | null;
  lessonsSection?: {
    title?: string | null;
    description?: string | null;
    showLessonNumbers?: boolean | null;
    lessons?: Lessons;
  };
  courses?: Courses;
  schedules?: Schedules;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  rating: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  icon?:
    | T
    | {
        fileIcon?: T;
        lucideIcon?: T;
      };
  title?: T;
  description?: T;
  content?: T;
  duration?: T;
  price?: T;
  location?: T;
  additionalInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        id?: T;
      };
  note?: T;
  serviceType?: T;
  lessonsSection?:
    | T
    | {
        title?: T;
        description?: T;
        showLessonNumbers?: T;
        lessons?: T | LessonsSelect<T>;
      };
  courses?: T | CoursesSelect<T>;
  schedules?: T | SchedulesSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  additionalInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        id?: T;
      };
  lessonsSection?:
    | T
    | {
        title?: T;
        description?: T;
        showLessonNumbers?: T;
        lessons?: T | LessonsSelect<T>;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  courseIndex?: T;
  status?: T;
  hasLimitedSpots?: T;
  numberOfSpots?: T;
  scheduleItems?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        lesson?: T;
        notes?: T;
        status?: T;
        hasLimitedSpots?: T;
        numberOfSpots?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  rating?: T;
  content?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: string;
  hero: Hero;
  services: Services;
  reviews: Reviews;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  title: string;
  quote?: string | null;
  subtitle?: string | null;
  heroImage?: (string | null) | Media;
  ctaButtons?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link".
 */
export interface Link {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?: ('/' | '/aktualni-sluzby' | '/sluzby' | '/o-mne' | '/kontakt') | null;
  url?: string | null;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services".
 */
export interface Services {
  title: string;
  subtitle?: string | null;
  services?:
    | {
        item?: {
          relationTo: 'services';
          value: string | Service;
        } | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews".
 */
export interface Reviews {
  title: string;
  subtitle?: string | null;
  reviews?:
    | {
        reference?: {
          relationTo: 'reviews';
          value: string | Review;
        } | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: string;
  pageHeader: PageHeader;
  serviceSections?:
    | {
        servicesSection?: {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          serviceSectionItems?:
            | {
                item: {
                  relationTo: 'services';
                  value: string | Service;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageHeader".
 */
export interface PageHeader {
  title: string;
  subtitle?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weeklyScheduledServicesPage".
 */
export interface WeeklyScheduledServicesPage {
  id: string;
  pageHeader: PageHeader;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: string;
  pageHeader: PageHeader;
  image?: (string | null) | Media;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  ctaSection: {
    title: string;
    subtitle?: string | null;
    ctaButtons?:
      | {
          link: Link;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: string;
  pageHeader: PageHeader;
  contactInfo?:
    | {
        icon?: string | null;
        title?: string | null;
        value?: string | null;
        formattedValue?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        valueType?: ('text' | 'formattedText' | 'email' | 'phone' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: {
    img?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  headerTitle: string;
  headerSubTitle?: string | null;
  phone: string;
  email: string;
  navItems?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: {
    img?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  footerTitle: string;
  footerSubTitle?: string | null;
  quickLinks: {
    title: string;
    links: {
      link: Link;
      id?: string | null;
    }[];
  };
  contact: {
    title: string;
    phone?: string | null;
    email?: string | null;
    adress?: string | null;
  };
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: string;
  bannerEnabled?: boolean | null;
  modalEnabled?: boolean | null;
  banner?: AnnouncementBanner;
  modal?: AnnouncementModal;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementBanner".
 */
export interface AnnouncementBanner {
  message: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'info' | 'warning' | 'success' | 'error';
  dismissible?: boolean | null;
  showOnce?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementModal".
 */
export interface AnnouncementModal {
  title?: string | null;
  message: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'info' | 'warning' | 'success' | 'error';
  dismissible?: boolean | null;
  showOnce?: boolean | null;
  buttonText?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?: T | HeroSelect<T>;
  services?: T | ServicesSelect1<T>;
  reviews?: T | ReviewsSelect1<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  quote?: T;
  subtitle?: T;
  heroImage?: T;
  ctaButtons?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_select".
 */
export interface LinkSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  reference?: T;
  url?: T;
  label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services_select".
 */
export interface ServicesSelect1<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  services?:
    | T
    | {
        item?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews_select".
 */
export interface ReviewsSelect1<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  reviews?:
    | T
    | {
        reference?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  serviceSections?:
    | T
    | {
        servicesSection?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              serviceSectionItems?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageHeader_select".
 */
export interface PageHeaderSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weeklyScheduledServicesPage_select".
 */
export interface WeeklyScheduledServicesPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  image?: T;
  title?: T;
  content?: T;
  ctaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaButtons?:
          | T
          | {
              link?: T | LinkSelect<T>;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  contactInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        formattedValue?: T;
        valueType?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        img?: T;
        lucideIcon?: T;
      };
  headerTitle?: T;
  headerSubTitle?: T;
  phone?: T;
  email?: T;
  navItems?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        img?: T;
        lucideIcon?: T;
      };
  footerTitle?: T;
  footerSubTitle?: T;
  quickLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?: T | LinkSelect<T>;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        phone?: T;
        email?: T;
        adress?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  bannerEnabled?: T;
  modalEnabled?: T;
  banner?: T | AnnouncementBannerSelect<T>;
  modal?: T | AnnouncementModalSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementBanner_select".
 */
export interface AnnouncementBannerSelect<T extends boolean = true> {
  message?: T;
  type?: T;
  dismissible?: T;
  showOnce?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementModal_select".
 */
export interface AnnouncementModalSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  dismissible?: T;
  showOnce?: T;
  buttonText?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}