/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export type Announcements =
  | {
      title?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      date?: string | null;
      image?: (string | null) | Media;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export type Lessons =
  | {
      title: string;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export type Courses =
  | {
      name?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      additionalInfo?:
        | {
            icon?: string | null;
            title: string;
            value: string;
            id?: string | null;
          }[]
        | null;
      lessonsSection?: {
        title?: string | null;
        description?: string | null;
        showLessonNumbers?: boolean | null;
        lessons?: Lessons;
      };
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export type Schedules =
  | {
      title?: string | null;
      description?: string | null;
      /**
       * Vyberte kurz - v termínech pak můžete vybírat lekce
       */
      courseIndex?: string | null;
      status?: ServiceStatus;
      hasLimitedSpots?: boolean | null;
      numberOfSpots?: number | null;
      scheduleItems?:
        | {
            startDate: string;
            endDate: string;
            /**
             * Vyberte lekci nebo zadejte vlastní název
             */
            lesson: string;
            notes?: string | null;
            status?: ServiceStatus;
            hasLimitedSpots?: boolean | null;
            numberOfSpots?: number | null;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceStatus".
 */
export type ServiceStatus = ('scheduled' | 'inProgress' | 'booked' | 'cancelled') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    reviews: Review;
    downloads: Download;
    users: User;
    media: Media;
    blogs: Blog;
    'blog-categories': BlogCategory;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'downloads' | 'media';
    };
  };
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('cs' | 'en') | ('cs' | 'en')[];
  globals: {
    homePage: HomePage;
    servicesPage: ServicesPage;
    weeklyScheduledServicesPage: WeeklyScheduledServicesPage;
    aboutPage: AboutPage;
    contactPage: ContactPage;
    downloadsPage: DownloadsPage;
    blogPage: BlogPage;
    header: Header;
    footer: Footer;
    announcement: Announcement;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    weeklyScheduledServicesPage: WeeklyScheduledServicesPageSelect<false> | WeeklyScheduledServicesPageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    downloadsPage: DownloadsPageSelect<false> | DownloadsPageSelect<true>;
    blogPage: BlogPageSelect<false> | BlogPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
  };
  locale: 'cs' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Automaticky generovaný z názvu služby. Lze upravit.
   */
  slug: string;
  title: string;
  icon?: {
    fileIcon?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  card: {
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    additionalInfo?:
      | {
          title: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  detail: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    additionalInfo?:
      | {
          icon?: string | null;
          title: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    note?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    benefitsSection?: {
      enabled?: boolean | null;
      title?: string | null;
      benefits?:
        | {
            title: string;
            id?: string | null;
          }[]
        | null;
    };
    packageSection?: {
      enabled?: boolean | null;
      title?: string | null;
      description?: string | null;
      packages?:
        | {
            title: string;
            price?: string | null;
            includedOffers?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
    announcementsSection?: {
      enabled?: boolean | null;
      announcements?: Announcements;
    };
  };
  serviceType?: ('courses' | 'lessons') | null;
  lessonsSection?: {
    title?: string | null;
    description?: string | null;
    showLessonNumbers?: boolean | null;
    lessons?: Lessons;
  };
  courses?: Courses;
  schedules?: Schedules;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'downloads';
          value: string | Download;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('downloads' | 'media')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: string;
  title: string;
  description?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  rating: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  /**
   * Automaticky generovaný z názvu služby. Lze upravit.
   */
  slug: string;
  title: string;
  headImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  author?: string | null;
  category?: (string | null) | BlogCategory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'downloads';
        value: string | Download;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  icon?:
    | T
    | {
        fileIcon?: T;
        lucideIcon?: T;
      };
  card?:
    | T
    | {
        description?: T;
        additionalInfo?:
          | T
          | {
              title?: T;
              value?: T;
              id?: T;
            };
      };
  detail?:
    | T
    | {
        content?: T;
        additionalInfo?:
          | T
          | {
              icon?: T;
              title?: T;
              value?: T;
              id?: T;
            };
        note?: T;
        benefitsSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              benefits?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
            };
        packageSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              description?: T;
              packages?:
                | T
                | {
                    title?: T;
                    price?: T;
                    includedOffers?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        announcementsSection?:
          | T
          | {
              enabled?: T;
              announcements?: T | AnnouncementsSelect<T>;
            };
      };
  serviceType?: T;
  lessonsSection?:
    | T
    | {
        title?: T;
        description?: T;
        showLessonNumbers?: T;
        lessons?: T | LessonsSelect<T>;
      };
  courses?: T | CoursesSelect<T>;
  schedules?: T | SchedulesSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  image?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  additionalInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        id?: T;
      };
  lessonsSection?:
    | T
    | {
        title?: T;
        description?: T;
        showLessonNumbers?: T;
        lessons?: T | LessonsSelect<T>;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  courseIndex?: T;
  status?: T;
  hasLimitedSpots?: T;
  numberOfSpots?: T;
  scheduleItems?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        lesson?: T;
        notes?: T;
        status?: T;
        hasLimitedSpots?: T;
        numberOfSpots?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  rating?: T;
  content?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  headImage?: T;
  content?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: string;
  hero: Hero;
  services: Services;
  reviews: Reviews;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  title: string;
  quote?: string | null;
  subtitle?: string | null;
  switchInterval?: number | null;
  heroImages?:
    | {
        heroImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link".
 */
export interface Link {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?: ('/' | '/aktualni-sluzby' | '/sluzby' | '/o-mne' | '/kontakt' | '/ke-stazeni' | '/blog') | null;
  url?: string | null;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services".
 */
export interface Services {
  title: string;
  subtitle?: string | null;
  services?:
    | {
        item?: {
          relationTo: 'services';
          value: string | Service;
        } | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews".
 */
export interface Reviews {
  title: string;
  subtitle?: string | null;
  reviews?:
    | {
        reference?: {
          relationTo: 'reviews';
          value: string | Review;
        } | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: string;
  pageHeader: PageHeader;
  serviceSections?:
    | {
        servicesSection?: {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          serviceSectionItems?:
            | {
                item: {
                  relationTo: 'services';
                  value: string | Service;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageHeader".
 */
export interface PageHeader {
  title: string;
  subtitle?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weeklyScheduledServicesPage".
 */
export interface WeeklyScheduledServicesPage {
  id: string;
  pageHeader: PageHeader;
  infoSection: {
    title: string;
    description?: string | null;
    announcementsSection?: {
      enabled?: boolean | null;
      announcements?: Announcements;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: string;
  pageHeader: PageHeader;
  image?: (string | null) | Media;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  myValuesSection?: {
    showMyValues?: boolean | null;
    title?: string | null;
    values?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection: {
    title: string;
    subtitle?: string | null;
    ctaButtons?:
      | {
          link: Link;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: string;
  pageHeader: PageHeader;
  contactInfo?:
    | {
        icon?: string | null;
        title?: string | null;
        value?: string | null;
        formattedValue?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        valueType?: ('text' | 'formattedText' | 'email' | 'phone' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloadsPage".
 */
export interface DownloadsPage {
  id: string;
  pageHeader: PageHeader;
  passwordHash?: string | null;
  /**
   * Zadejte heslo a uložte. Po uložení se pole vyprázdní.
   */
  newPassword?: string | null;
  downloads?:
    | {
        file?: (string | null) | Download;
        id?: string | null;
      }[]
    | null;
  important?: {
    title?: string | null;
    infoItems?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPage".
 */
export interface BlogPage {
  id: string;
  pageHeader: PageHeader;
  blogPosts?:
    | {
        blogPost?: (string | null) | Blog;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: {
    img?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  headerTitle: string;
  headerSubTitle?: string | null;
  phone: string;
  email: string;
  navItems?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: {
    img?: (string | null) | Media;
    lucideIcon?: string | null;
  };
  footerTitle: string;
  footerSubTitle?: string | null;
  downloadsSection?: {
    enabled?: boolean | null;
    title?: string | null;
    link?: string | null;
    description?: string | null;
  };
  contact: {
    title: string;
    phone?: string | null;
    email?: string | null;
    adress?: string | null;
  };
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: string;
  bannerEnabled?: boolean | null;
  modalEnabled?: boolean | null;
  banner?: AnnouncementBanner;
  modal?: AnnouncementModal;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementBanner".
 */
export interface AnnouncementBanner {
  message: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'info' | 'warning' | 'success' | 'error';
  dismissible?: boolean | null;
  showOnce?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementModal".
 */
export interface AnnouncementModal {
  title?: string | null;
  message: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'info' | 'warning' | 'success' | 'error';
  dismissible?: boolean | null;
  showOnce?: boolean | null;
  buttonText?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?: T | HeroSelect<T>;
  services?: T | ServicesSelect1<T>;
  reviews?: T | ReviewsSelect1<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  quote?: T;
  subtitle?: T;
  switchInterval?: T;
  heroImages?:
    | T
    | {
        heroImage?: T;
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_select".
 */
export interface LinkSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  reference?: T;
  url?: T;
  label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services_select".
 */
export interface ServicesSelect1<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  services?:
    | T
    | {
        item?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Reviews_select".
 */
export interface ReviewsSelect1<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  reviews?:
    | T
    | {
        reference?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  serviceSections?:
    | T
    | {
        servicesSection?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              serviceSectionItems?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageHeader_select".
 */
export interface PageHeaderSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weeklyScheduledServicesPage_select".
 */
export interface WeeklyScheduledServicesPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  infoSection?:
    | T
    | {
        title?: T;
        description?: T;
        announcementsSection?:
          | T
          | {
              enabled?: T;
              announcements?: T | AnnouncementsSelect<T>;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  image?: T;
  title?: T;
  content?: T;
  myValuesSection?:
    | T
    | {
        showMyValues?: T;
        title?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaButtons?:
          | T
          | {
              link?: T | LinkSelect<T>;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  contactInfo?:
    | T
    | {
        icon?: T;
        title?: T;
        value?: T;
        formattedValue?: T;
        valueType?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloadsPage_select".
 */
export interface DownloadsPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  passwordHash?: T;
  newPassword?: T;
  downloads?:
    | T
    | {
        file?: T;
        id?: T;
      };
  important?:
    | T
    | {
        title?: T;
        infoItems?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPage_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  pageHeader?: T | PageHeaderSelect<T>;
  blogPosts?:
    | T
    | {
        blogPost?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        img?: T;
        lucideIcon?: T;
      };
  headerTitle?: T;
  headerSubTitle?: T;
  phone?: T;
  email?: T;
  navItems?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        img?: T;
        lucideIcon?: T;
      };
  footerTitle?: T;
  footerSubTitle?: T;
  downloadsSection?:
    | T
    | {
        enabled?: T;
        title?: T;
        link?: T;
        description?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        phone?: T;
        email?: T;
        adress?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  bannerEnabled?: T;
  modalEnabled?: T;
  banner?: T | AnnouncementBannerSelect<T>;
  modal?: T | AnnouncementModalSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementBanner_select".
 */
export interface AnnouncementBannerSelect<T extends boolean = true> {
  message?: T;
  type?: T;
  dismissible?: T;
  showOnce?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcementModal_select".
 */
export interface AnnouncementModalSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  dismissible?: T;
  showOnce?: T;
  buttonText?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}